name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # ... other jobs ...
      - name: Deploy Application via SSH
        uses: falling42/ssh-deploy@v0.2.1
        with:
          use_screen: 'yes' # Defaults to no, omit if not needed
          ssh_host: ${{ secrets.REMOTE_HOST }}
          ssh_user:  ${{ secrets.REMOTE_USER }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          # ssh_port: 23456 # Default is 22, omit if not needed
          use_jump_host: 'no' # Defaults to no, omit if not needed
          transfer_files: 'yes' # Defaults to yes, as transferring files is a core function of this action :)
          # source_file_path: './build/app.jar' # Artifact from an upstream job
          destination_path: ${{ secrets.REMOTE_TARGET }}
